name:                99questions
version:             0.1.0.0
github:              "githubuser/99-questions"
license:             MIT
author:              "Rafael Fiume"
maintainer:          "rafael.fiume@yahoo.it"
copyright:           "2018 Rafael Fiume"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis:            Playing around with 99 questions
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/99-questions#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl

library:
  source-dirs: src

executables:
  99questions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -fno-warn-type-defaults
    dependencies:
      - 99questions

tests:
  99questions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -fno-warn-type-defaults
    dependencies:
      - 99questions
      - tasty
      - tasty-auto
      - tasty-quickcheck
      - tasty-hspec
      - tasty-html
      - QuickCheck
      - hspec == 2.*
